#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="${BASH_SOURCE[0]:-$0}"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"

: "${HEIRLOOM_VERTEX_VALIDATE_MODE:=quick}"
: "${HEIRLOOM_VERTEX_ACCELERATOR_TYPE:=NVIDIA_A100_80GB}"
: "${HEIRLOOM_VERTEX_ACCELERATOR_COUNT:=4}"
: "${CARGO_INCREMENTAL:=0}"

: "${HEIRLOOM_REQUIRE_GPU:=1}"
: "${HEIRLOOM_GPU_SMOKE_DEVICES:=all}"
: "${HEIRLOOM_COLLECT_GPU_TOPOLOGY:=1}"
: "${HEIRLOOM_RUN_TENSOR_CORE_PROBE:=0}"
: "${HEIRLOOM_RUN_CUDA_STORAGE_TESTS:=0}"
: "${HEIRLOOM_RUN_QUICK_CLIPPY:=0}"

: "${HEIRLOOM_RUN_NCCL_PROBE:=1}"
: "${HEIRLOOM_NCCL_PROBE_DEVICES:=cuda:0,cuda:1,cuda:2,cuda:3}"
: "${HEIRLOOM_NCCL_PROBE_KIND:=all-reduce}"
: "${HEIRLOOM_NCCL_CUMEM_ENABLE:=0}"
: "${HEIRLOOM_NCCL_P2P_DISABLE:=1}"

: "${HEIRLOOM_RUN_LEARNING_SANITY_SWEEP:=1}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_LRS:=0.015,0.0125,0.01,0.0075}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_GRAD_ACCUMULATION_STEPS:=1,2}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_STEPS:=48}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_BATCH:=2}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_BLOCK:=8}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_D_MODEL:=16}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_HEADS:=2}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_FF:=32}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_VOCAB:=280}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_SHARD_TOKENS:=512}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_SEED:=7}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_DEVICES:=cuda:0,cuda:1,cuda:2,cuda:3}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_DISTRIBUTED:=nccl}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_PRECISION:=amp-bf16}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_LOG_EVERY:=48}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_DDP_INIT_TIMEOUT_SECS:=180}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_DDP_CHECKSUM_EVERY:=16}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_MIN_LOSS_REDUCTION:=0.0}"
: "${HEIRLOOM_LEARNING_SANITY_SWEEP_MIN_BEST_LOSS_REDUCTION:=__HEIRLOOM_UNSET__}"

export HEIRLOOM_VERTEX_VALIDATE_MODE
export HEIRLOOM_VERTEX_ACCELERATOR_TYPE
export HEIRLOOM_VERTEX_ACCELERATOR_COUNT
export CARGO_INCREMENTAL
export HEIRLOOM_REQUIRE_GPU
export HEIRLOOM_GPU_SMOKE_DEVICES
export HEIRLOOM_COLLECT_GPU_TOPOLOGY
export HEIRLOOM_RUN_TENSOR_CORE_PROBE
export HEIRLOOM_RUN_CUDA_STORAGE_TESTS
export HEIRLOOM_RUN_QUICK_CLIPPY
export HEIRLOOM_RUN_NCCL_PROBE
export HEIRLOOM_NCCL_PROBE_DEVICES
export HEIRLOOM_NCCL_PROBE_KIND
export HEIRLOOM_NCCL_CUMEM_ENABLE
export HEIRLOOM_NCCL_P2P_DISABLE
export HEIRLOOM_RUN_LEARNING_SANITY_SWEEP
export HEIRLOOM_LEARNING_SANITY_SWEEP_LRS
export HEIRLOOM_LEARNING_SANITY_SWEEP_GRAD_ACCUMULATION_STEPS
export HEIRLOOM_LEARNING_SANITY_SWEEP_STEPS
export HEIRLOOM_LEARNING_SANITY_SWEEP_BATCH
export HEIRLOOM_LEARNING_SANITY_SWEEP_BLOCK
export HEIRLOOM_LEARNING_SANITY_SWEEP_D_MODEL
export HEIRLOOM_LEARNING_SANITY_SWEEP_HEADS
export HEIRLOOM_LEARNING_SANITY_SWEEP_FF
export HEIRLOOM_LEARNING_SANITY_SWEEP_VOCAB
export HEIRLOOM_LEARNING_SANITY_SWEEP_SHARD_TOKENS
export HEIRLOOM_LEARNING_SANITY_SWEEP_SEED
export HEIRLOOM_LEARNING_SANITY_SWEEP_DEVICES
export HEIRLOOM_LEARNING_SANITY_SWEEP_DISTRIBUTED
export HEIRLOOM_LEARNING_SANITY_SWEEP_PRECISION
export HEIRLOOM_LEARNING_SANITY_SWEEP_LOG_EVERY
export HEIRLOOM_LEARNING_SANITY_SWEEP_DDP_INIT_TIMEOUT_SECS
export HEIRLOOM_LEARNING_SANITY_SWEEP_DDP_CHECKSUM_EVERY
export HEIRLOOM_LEARNING_SANITY_SWEEP_MIN_LOSS_REDUCTION
export HEIRLOOM_LEARNING_SANITY_SWEEP_MIN_BEST_LOSS_REDUCTION

exec zsh "$SCRIPT_DIR/submit_vertex_heirloom_validate.sh"
