#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

: "${HEIRLOOM_VERTEX_VALIDATE_MODE:=quick}"
: "${HEIRLOOM_VERTEX_ACCELERATOR_TYPE:=NVIDIA_A100_80GB}"
: "${HEIRLOOM_VERTEX_ACCELERATOR_COUNT:=4}"
: "${HEIRLOOM_RUN_QUICK_CLIPPY:=1}"
: "${HEIRLOOM_RUN_CUDA_STORAGE_TESTS:=0}"
: "${HEIRLOOM_RUN_TENSOR_CORE_MICROBENCH:=0}"

: "${HEIRLOOM_GPU_SMOKE_DEVICES:=all}"
: "${HEIRLOOM_RUN_NCCL_PROBE:=1}"
: "${HEIRLOOM_NCCL_PROBE_DEVICES:=cuda:0,cuda:1,cuda:2,cuda:3}"
: "${HEIRLOOM_NCCL_PROBE_KIND:=all-reduce}"

: "${HEIRLOOM_RUN_CUDA_TRAIN_LM_FIXTURE:=1}"
: "${HEIRLOOM_CUDA_FIXTURE_DEVICES:=cuda:0,cuda:1,cuda:2,cuda:3}"
: "${HEIRLOOM_CUDA_FIXTURE_DISTRIBUTED:=nccl}"
: "${HEIRLOOM_CUDA_FIXTURE_PRECISION:=amp-bf16}"
: "${HEIRLOOM_CUDA_FIXTURE_BATCH_SIZE:=4}"
: "${HEIRLOOM_CUDA_FIXTURE_BLOCK_SIZE:=512}"
: "${HEIRLOOM_CUDA_FIXTURE_D_MODEL:=1024}"
: "${HEIRLOOM_CUDA_FIXTURE_N_HEADS:=16}"
: "${HEIRLOOM_CUDA_FIXTURE_FF_HIDDEN:=4096}"
: "${HEIRLOOM_CUDA_FIXTURE_STEPS:=10}"
: "${HEIRLOOM_CUDA_FIXTURE_RESUME_STEPS:=1}"

: "${HEIRLOOM_CUDA_TENSOR_CORE_CP_ASYNC_GEMM:=1}"
: "${HEIRLOOM_REQUIRE_CUDA_TENSOR_CORE_CP_ASYNC_GEMM:=1}"
: "${HEIRLOOM_CUDA_FLASH_BF16_ATTENTION:=1}"
: "${HEIRLOOM_CUDA_FLASH_BF16_ATTENTION_TENSOR_CORE:=1}"
: "${HEIRLOOM_CUDA_FLASH_BF16_ATTENTION_BACKWARD:=1}"
: "${HEIRLOOM_CUDA_FLASH_BF16_ATTENTION_TIMING:=1}"
: "${HEIRLOOM_REQUIRE_FLASH_BF16_ATTENTION:=1}"
: "${HEIRLOOM_EXPECT_FLASH_BF16_ATTENTION:=1}"
: "${HEIRLOOM_REQUIRE_TENSOR_CORES:=1}"
: "${HEIRLOOM_EXPECT_TENSOR_CORES:=1}"
: "${HEIRLOOM_EXPECT_ATTENTION_TENSOR_CORES:=1}"

export HEIRLOOM_VERTEX_VALIDATE_MODE
export HEIRLOOM_VERTEX_ACCELERATOR_TYPE
export HEIRLOOM_VERTEX_ACCELERATOR_COUNT
export HEIRLOOM_RUN_QUICK_CLIPPY
export HEIRLOOM_RUN_CUDA_STORAGE_TESTS
export HEIRLOOM_RUN_TENSOR_CORE_MICROBENCH
export HEIRLOOM_GPU_SMOKE_DEVICES
export HEIRLOOM_RUN_NCCL_PROBE
export HEIRLOOM_NCCL_PROBE_DEVICES
export HEIRLOOM_NCCL_PROBE_KIND
export HEIRLOOM_RUN_CUDA_TRAIN_LM_FIXTURE
export HEIRLOOM_CUDA_FIXTURE_DEVICES
export HEIRLOOM_CUDA_FIXTURE_DISTRIBUTED
export HEIRLOOM_CUDA_FIXTURE_PRECISION
export HEIRLOOM_CUDA_FIXTURE_BATCH_SIZE
export HEIRLOOM_CUDA_FIXTURE_BLOCK_SIZE
export HEIRLOOM_CUDA_FIXTURE_D_MODEL
export HEIRLOOM_CUDA_FIXTURE_N_HEADS
export HEIRLOOM_CUDA_FIXTURE_FF_HIDDEN
export HEIRLOOM_CUDA_FIXTURE_STEPS
export HEIRLOOM_CUDA_FIXTURE_RESUME_STEPS
export HEIRLOOM_CUDA_TENSOR_CORE_CP_ASYNC_GEMM
export HEIRLOOM_REQUIRE_CUDA_TENSOR_CORE_CP_ASYNC_GEMM
export HEIRLOOM_CUDA_FLASH_BF16_ATTENTION
export HEIRLOOM_CUDA_FLASH_BF16_ATTENTION_TENSOR_CORE
export HEIRLOOM_CUDA_FLASH_BF16_ATTENTION_BACKWARD
export HEIRLOOM_CUDA_FLASH_BF16_ATTENTION_TIMING
export HEIRLOOM_REQUIRE_FLASH_BF16_ATTENTION
export HEIRLOOM_EXPECT_FLASH_BF16_ATTENTION
export HEIRLOOM_REQUIRE_TENSOR_CORES
export HEIRLOOM_EXPECT_TENSOR_CORES
export HEIRLOOM_EXPECT_ATTENTION_TENSOR_CORES

exec zsh "$SCRIPT_DIR/submit_vertex_heirloom_validate.sh"
