#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="${BASH_SOURCE[0]:-$0}"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"

: "${HEIRLOOM_VERTEX_VALIDATE_MODE:=quick}"
: "${HEIRLOOM_VERTEX_ACCELERATOR_TYPE:=NVIDIA_A100_80GB}"
: "${HEIRLOOM_VERTEX_ACCELERATOR_COUNT:=4}"
: "${CARGO_INCREMENTAL:=0}"

: "${HEIRLOOM_REQUIRE_GPU:=1}"
: "${HEIRLOOM_GPU_SMOKE_DEVICES:=all}"
: "${HEIRLOOM_COLLECT_GPU_TOPOLOGY:=1}"
: "${HEIRLOOM_RUN_TENSOR_CORE_PROBE:=0}"
: "${HEIRLOOM_RUN_CUDA_STORAGE_TESTS:=0}"
: "${HEIRLOOM_RUN_QUICK_CLIPPY:=0}"

: "${HEIRLOOM_RUN_NCCL_PROBE:=1}"
: "${HEIRLOOM_NCCL_PROBE_DEVICES:=cuda:0,cuda:1,cuda:2,cuda:3}"
: "${HEIRLOOM_NCCL_PROBE_KIND:=all-reduce}"
: "${HEIRLOOM_NCCL_CUMEM_ENABLE:=0}"
: "${HEIRLOOM_NCCL_P2P_DISABLE:=1}"

: "${HEIRLOOM_RUN_QB_TOKENIZER_HARDPATH:=1}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_MODE:=full}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_VOCAB:=32768}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_TARGET_TOKENS:=2500000}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_MATERIALIZE_MODE:=full}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_SAMPLE_BYTES:=6000000000}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_TOKENIZER_PATH:=}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_PREPARED_MANIFEST:=}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_PREPARED_SELECTED_DOCS:=}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_TOKENIZER_ONLY:=0}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_SHARD_TOKENS:=1000000}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_VALID_FRACTION:=0.1}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_LEARNING_SANITY:=1}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_LEARNING_SANITY_MIN_LOSS_REDUCTION:=0.0}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_LEARNING_SANITY_MIN_BLEND_SOURCES:=5}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_LEARNING_SANITY_REQUIRE_PRODUCTION_GATE:=true}"

: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_DEVICE:=cuda:0}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_DEVICES:=cuda:0,cuda:1,cuda:2,cuda:3}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_DISTRIBUTED:=nccl}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_PRECISION:=amp-bf16}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_STEPS:=2}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_RESUME_STEPS:=1}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_BATCH:=2}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_GRAD_ACCUMULATION_STEPS:=2}"
: "${HEIRLOOM_QB_TOKENIZER_HARDPATH_LR:=0.015}"

QB1_SOURCE_ROOT="gs://project-49b1b523-d248-434f-bd4-vecl-qb-artifacts/heirloom/qb-native-pretraining-v1/source-slices-1b-rehearsal"
: "${HEIRLOOM_QB_TOKENIZER_DOLMA_PATH:=${QB1_SOURCE_ROOT}/dolma-v1_7/}"
: "${HEIRLOOM_QB_TOKENIZER_NEMOTRON_CC_PATH:=${QB1_SOURCE_ROOT}/nemotron-cc-high-actual/nemotron-cc-high-actual-sample.jsonl}"
: "${HEIRLOOM_QB_TOKENIZER_OLMO3_PATH:=${QB1_SOURCE_ROOT}/dolma3-dolmino-mix-100b-1125/}"
: "${HEIRLOOM_QB_TOKENIZER_NEMOTRON_CC_MATH_PATH:=${QB1_SOURCE_ROOT}/nemotron-cc-math/nemotron-cc-math-sample.jsonl}"
: "${HEIRLOOM_QB_TOKENIZER_QB_V1_HARD_PATH:=${QB1_SOURCE_ROOT}/vecl-qb-v1-hard/corpus.jsonl}"

export HEIRLOOM_VERTEX_VALIDATE_MODE
export HEIRLOOM_VERTEX_ACCELERATOR_TYPE
export HEIRLOOM_VERTEX_ACCELERATOR_COUNT
export CARGO_INCREMENTAL
export HEIRLOOM_REQUIRE_GPU
export HEIRLOOM_GPU_SMOKE_DEVICES
export HEIRLOOM_COLLECT_GPU_TOPOLOGY
export HEIRLOOM_RUN_TENSOR_CORE_PROBE
export HEIRLOOM_RUN_CUDA_STORAGE_TESTS
export HEIRLOOM_RUN_QUICK_CLIPPY
export HEIRLOOM_RUN_NCCL_PROBE
export HEIRLOOM_NCCL_PROBE_DEVICES
export HEIRLOOM_NCCL_PROBE_KIND
export HEIRLOOM_NCCL_CUMEM_ENABLE
export HEIRLOOM_NCCL_P2P_DISABLE
export HEIRLOOM_RUN_QB_TOKENIZER_HARDPATH
export HEIRLOOM_QB_TOKENIZER_HARDPATH_MODE
export HEIRLOOM_QB_TOKENIZER_HARDPATH_VOCAB
export HEIRLOOM_QB_TOKENIZER_HARDPATH_TARGET_TOKENS
export HEIRLOOM_QB_TOKENIZER_HARDPATH_MATERIALIZE_MODE
export HEIRLOOM_QB_TOKENIZER_HARDPATH_SAMPLE_BYTES
export HEIRLOOM_QB_TOKENIZER_HARDPATH_TOKENIZER_PATH
export HEIRLOOM_QB_TOKENIZER_HARDPATH_PREPARED_MANIFEST
export HEIRLOOM_QB_TOKENIZER_HARDPATH_PREPARED_SELECTED_DOCS
export HEIRLOOM_QB_TOKENIZER_HARDPATH_TOKENIZER_ONLY
export HEIRLOOM_QB_TOKENIZER_HARDPATH_SHARD_TOKENS
export HEIRLOOM_QB_TOKENIZER_HARDPATH_VALID_FRACTION
export HEIRLOOM_QB_TOKENIZER_HARDPATH_LEARNING_SANITY
export HEIRLOOM_QB_TOKENIZER_HARDPATH_LEARNING_SANITY_MIN_LOSS_REDUCTION
export HEIRLOOM_QB_TOKENIZER_HARDPATH_LEARNING_SANITY_MIN_BLEND_SOURCES
export HEIRLOOM_QB_TOKENIZER_HARDPATH_LEARNING_SANITY_REQUIRE_PRODUCTION_GATE
export HEIRLOOM_QB_TOKENIZER_HARDPATH_DEVICE
export HEIRLOOM_QB_TOKENIZER_HARDPATH_DEVICES
export HEIRLOOM_QB_TOKENIZER_HARDPATH_DISTRIBUTED
export HEIRLOOM_QB_TOKENIZER_HARDPATH_PRECISION
export HEIRLOOM_QB_TOKENIZER_HARDPATH_STEPS
export HEIRLOOM_QB_TOKENIZER_HARDPATH_RESUME_STEPS
export HEIRLOOM_QB_TOKENIZER_HARDPATH_BATCH
export HEIRLOOM_QB_TOKENIZER_HARDPATH_GRAD_ACCUMULATION_STEPS
export HEIRLOOM_QB_TOKENIZER_HARDPATH_LR
export HEIRLOOM_QB_TOKENIZER_DOLMA_PATH
export HEIRLOOM_QB_TOKENIZER_NEMOTRON_CC_PATH
export HEIRLOOM_QB_TOKENIZER_OLMO3_PATH
export HEIRLOOM_QB_TOKENIZER_NEMOTRON_CC_MATH_PATH
export HEIRLOOM_QB_TOKENIZER_QB_V1_HARD_PATH

exec zsh "$SCRIPT_DIR/submit_vertex_heirloom_validate.sh"
